# Generated by Django 3.2.5 on 2021-12-15 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211214_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2021, 12, 15, 7, 15, 56, 704796, tzinfo=utc), upload_to='media/post/'),
            preserve_default=False,
        ),
    ]
